### ISSUE TITLE
can't import reaktoro macOS

### ISSUE THREAD

**Issue by dianabacon** [reaktoro/reaktoro#152]
I am running macOS Mojave.  I already had Anaconda installed.  I set up a new python 3.7 environment using conda 4.8.3.  I switched to the new environment and installed reaktoro using "conda install reaktoro" and it seemed to install correctly.  However, if I try to import reaktoro I get an error message:
>>> import reaktoro
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda2/envs/chem/lib/python3.7/site-packages/reaktoro/__init__.py", line 1, in <module>
    from reaktoro.PyReaktoro import *
ImportError: dlopen(/anaconda2/envs/chem/lib/python3.7/site-packages/reaktoro/PyReaktoro.cpython-37m-darwin.so, 2): Symbol not found: __ZN9ThermoFun12ThermoEngine25thermoPropertiesSubstanceEdRdNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE
  Referenced from: /anaconda2/envs/chem/lib/libReaktoro.dylib
  Expected in: /anaconda2/envs/chem/lib/libThermoFun.dylib
 in /anaconda2/envs/chem/lib/libReaktoro.dylib

**Comment by allanleal** [comment]
Hi, I just tried here in a High Sierra macOS system, and it worked. I'm puzzled why this is happening in your machine. Could you please try the installation again? Here were my steps:

```
conda create -n rkt reaktoro
```

The output was:

```
conda create -n rkt reaktoro
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.12
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /Users/allanleal/miniconda3/envs/rkt

  added / updated specs:
    - reaktoro


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-1.72.0               |   py38hbf1eeb5_0         345 KB  conda-forge
    boost-cpp-1.72.0           |       hdf9ef73_0        19.1 MB  conda-forge
    bzip2-1.0.8                |       h0b31af3_2         152 KB  conda-forge
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    certifi-2020.4.5.1         |   py38h32f6830_0         151 KB  conda-forge
    libblas-3.8.0              |      16_openblas          10 KB  conda-forge
    libcblas-3.8.0             |      16_openblas          10 KB  conda-forge
    libcxx-10.0.0              |       h1af66ff_2         1.0 MB  conda-forge
    libffi-3.2.1               |    h4a8c4bd_1007          42 KB  conda-forge
    liblapack-3.8.0            |      16_openblas          10 KB  conda-forge
    libopenblas-0.3.9          |       h3d69b6c_0         8.4 MB  conda-forge
    llvm-openmp-10.0.0         |       h28b9765_0         268 KB  conda-forge
    numpy-1.18.4               |   py38h1f821a2_0         5.1 MB  conda-forge
    openssl-1.1.1g             |       h0b31af3_0         1.9 MB  conda-forge
    pandas-1.0.3               |   py38h5fc983b_1        10.3 MB  conda-forge
    pip-20.1                   |     pyh9f0ad1d_0         1.1 MB  conda-forge
    python-3.8.2               |hd5f0129_7_cpython        31.7 MB  conda-forge
    python_abi-3.8             |           1_cp38           4 KB  conda-forge
    pytz-2020.1                |     pyh9f0ad1d_0         227 KB  conda-forge
    reaktoro-1.1.1             |   py38hd1966b5_0         5.3 MB  conda-forge
    setuptools-46.2.0          |   py38h32f6830_0         645 KB  conda-forge
    six-1.14.0                 |             py_1          13 KB  conda-forge
    thermofun-0.3.3            |   py38h5fc983b_0         1.3 MB  conda-forge
    tk-8.6.10                  |       hbbe82c9_0         3.3 MB  conda-forge
    wheel-0.34.2               |             py_1          24 KB  conda-forge
    xz-5.2.5                   |       h0b31af3_0         266 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        90.7 MB

The following NEW packages will be INSTALLED:

  boost              conda-forge/osx-64::boost-1.72.0-py38hbf1eeb5_0
  boost-cpp          conda-forge/osx-64::boost-cpp-1.72.0-hdf9ef73_0
  bzip2              conda-forge/osx-64::bzip2-1.0.8-h0b31af3_2
  ca-certificates    conda-forge/osx-64::ca-certificates-2020.4.5.1-hecc5488_0
  certifi            conda-forge/osx-64::certifi-2020.4.5.1-py38h32f6830_0
  icu                conda-forge/osx-64::icu-64.2-h6de7cb9_1
  libblas            conda-forge/osx-64::libblas-3.8.0-16_openblas
  libcblas           conda-forge/osx-64::libcblas-3.8.0-16_openblas
  libcxx             conda-forge/osx-64::libcxx-10.0.0-h1af66ff_2
  libffi             conda-forge/osx-64::libffi-3.2.1-h4a8c4bd_1007
  libgfortran        conda-forge/osx-64::libgfortran-4.0.0-2
  liblapack          conda-forge/osx-64::liblapack-3.8.0-16_openblas
  libopenblas        conda-forge/osx-64::libopenblas-0.3.9-h3d69b6c_0
  llvm-openmp        conda-forge/osx-64::llvm-openmp-10.0.0-h28b9765_0
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  numpy              conda-forge/osx-64::numpy-1.18.4-py38h1f821a2_0
  openssl            conda-forge/osx-64::openssl-1.1.1g-h0b31af3_0
  pandas             conda-forge/osx-64::pandas-1.0.3-py38h5fc983b_1
  pip                conda-forge/noarch::pip-20.1-pyh9f0ad1d_0
  python             conda-forge/osx-64::python-3.8.2-hd5f0129_7_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.1-py_0
  python_abi         conda-forge/osx-64::python_abi-3.8-1_cp38
  pytz               conda-forge/noarch::pytz-2020.1-pyh9f0ad1d_0
  readline           conda-forge/osx-64::readline-8.0-hcfe32e1_0
  reaktoro           conda-forge/osx-64::reaktoro-1.1.1-py38hd1966b5_0
  setuptools         conda-forge/osx-64::setuptools-46.2.0-py38h32f6830_0
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/osx-64::sqlite-3.30.1-h93121df_0
  thermofun          conda-forge/osx-64::thermofun-0.3.3-py38h5fc983b_0
  tk                 conda-forge/osx-64::tk-8.6.10-hbbe82c9_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/osx-64::xz-5.2.5-h0b31af3_0
  zlib               conda-forge/osx-64::zlib-1.2.11-h0b31af3_1006


Proceed ([y]/n)? y


Downloading and Extracting Packages
liblapack-3.8.0      | 10 KB     | ##################################### | 100% 
openssl-1.1.1g       | 1.9 MB    | ##################################### | 100% 
six-1.14.0           | 13 KB     | ##################################### | 100% 
setuptools-46.2.0    | 645 KB    | ##################################### | 100% 
reaktoro-1.1.1       | 5.3 MB    | ##################################### | 100% 
python_abi-3.8       | 4 KB      | ##################################### | 100% 
llvm-openmp-10.0.0   | 268 KB    | ##################################### | 100% 
boost-cpp-1.72.0     | 19.1 MB   | ##################################### | 100% 
wheel-0.34.2         | 24 KB     | ##################################### | 100% 
libcxx-10.0.0        | 1.0 MB    | ##################################### | 100% 
pandas-1.0.3         | 10.3 MB   | ##################################### | 100% 
python-3.8.2         | 31.7 MB   | ##################################### | 100% 
libblas-3.8.0        | 10 KB     | ##################################### | 100% 
certifi-2020.4.5.1   | 151 KB    | ##################################### | 100% 
libffi-3.2.1         | 42 KB     | ##################################### | 100% 
thermofun-0.3.3      | 1.3 MB    | ##################################### | 100% 
libcblas-3.8.0       | 10 KB     | ##################################### | 100% 
pytz-2020.1          | 227 KB    | ##################################### | 100% 
ca-certificates-2020 | 146 KB    | ##################################### | 100% 
bzip2-1.0.8          | 152 KB    | ##################################### | 100% 
pip-20.1             | 1.1 MB    | ##################################### | 100% 
libopenblas-0.3.9    | 8.4 MB    | ##################################### | 100% 
xz-5.2.5             | 266 KB    | ##################################### | 100% 
boost-1.72.0         | 345 KB    | ##################################### | 100% 
numpy-1.18.4         | 5.1 MB    | ##################################### | 100% 
tk-8.6.10            | 3.3 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate rkt
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

I then did:

```
conda activate rkt
python
>>> import reaktoro
```

and this worked fine. I'll be happy to investigate this further if the error persists.

**Comment by dianabacon** [comment]
That worked, thank you!
